# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Fields

# Model Form Field configuration
form: $/clake/userextended/models/field/fields.yaml

# Model Class name
modelClass: Clake\Userextended\Models\Field

# Default redirect location
defaultRedirect: clake/userextended/fields

