# ===================================
#  Form Field Definitions
# ===================================


country:
    label: rainlab.location::lang.country.label
    placeholder: rainlab.location::lang.country.select
    type: dropdown
    tab: Profile
    span: left

state:
    label: rainlab.location::lang.state.label
    placeholder: rainlab.location::lang.state.select
    type: dropdown
    tab: Profile
    span: right
    dependsOn: country