<?php namespace Clake\UserExtended\Updates;

use Clake\UserExtended\Models\Timezone;
use October\Rain\Database\Updates\Seeder;

class SeedTimeZones extends Seeder
{

    private $timezones = array(
        array('abbr'=>'UTC', 'name'=>'Coordinated Universal Time', 'utc'=>'UTC', 'offset'=>'0'),
        array('abbr'=>'BIT', 'name'=>'Baker Island Time', 'utc'=>'UTC-12', 'offset'=>'-12'),
        array('abbr'=>'NUT', 'name'=>'Niue Time', 'utc'=>'UTC-11', 'offset'=>'-11'),
        array('abbr'=>'SST', 'name'=>'Samoa Standard Time', 'utc'=>'UTC-11', 'offset'=>'-11'),
        array('abbr'=>'CKT', 'name'=>'Cook Island Time', 'utc'=>'UTC-10', 'offset'=>'-10'),
        array('abbr'=>'HAST', 'name'=>'Hawaii-Aleutian Standard Time', 'utc'=>'UTC-10', 'offset'=>'-10'),
        array('abbr'=>'HST', 'name'=>'Hawaii Standard Time', 'utc'=>'UTC-10', 'offset'=>'-10'),
        array('abbr'=>'TAHT', 'name'=>'Tahiti Time', 'utc'=>'UTC-10', 'offset'=>'-10'),
        array('abbr'=>'MART', 'name'=>'Marquesas Islands Time', 'utc'=>'UTC-09:30', 'offset'=>'-09:30'),
        array('abbr'=>'MIT', 'name'=>'Marquesas Islands Time', 'utc'=>'UTC-09:30', 'offset'=>'-09:30'),
        array('abbr'=>'AKST', 'name'=>'Alaska Standard Time', 'utc'=>'UTC-09', 'offset'=>'-9'),
        array('abbr'=>'GAMT', 'name'=>'Gambier Islands', 'utc'=>'UTC-09', 'offset'=>'-9'),
        array('abbr'=>'GIT', 'name'=>'Gambier Island Time', 'utc'=>'UTC-09', 'offset'=>'-9'),
        array('abbr'=>'HADT', 'name'=>'Hawaii-Aleutian Daylight Time', 'utc'=>'UTC-09', 'offset'=>'-9'),
        array('abbr'=>'AKDT', 'name'=>'Alaska Daylight Time', 'utc'=>'UTC-08', 'offset'=>'-8'),
        array('abbr'=>'CIST', 'name'=>'Clipperton Island Standard Time', 'utc'=>'UTC-08', 'offset'=>'-8'),
        array('abbr'=>'PST', 'name'=>'Pacific Standard Time (North America)', 'utc'=>'UTC-08', 'offset'=>'-8'),
        array('abbr'=>'MST', 'name'=>'Mountain Standard Time (North America)', 'utc'=>'UTC-07', 'offset'=>'-7'),
        array('abbr'=>'PDT', 'name'=>'Pacific Daylight Time (North America)', 'utc'=>'UTC-07', 'offset'=>'-7'),
        array('abbr'=>'CST', 'name'=>'Central Standard Time (North America)', 'utc'=>'UTC-06', 'offset'=>'-6'),
        array('abbr'=>'EAST', 'name'=>'Easter Island Standard Time', 'utc'=>'UTC-06', 'offset'=>'-6'),
        array('abbr'=>'GALT', 'name'=>'Galapagos Time', 'utc'=>'UTC-06', 'offset'=>'-6'),
        array('abbr'=>'MDT', 'name'=>'Mountain Daylight Time (North America)', 'utc'=>'UTC-06', 'offset'=>'-6'),
        array('abbr'=>'CDT', 'name'=>'Central Daylight Time (North America)', 'utc'=>'UTC-05', 'offset'=>'-5'),
        array('abbr'=>'COT', 'name'=>'Colombia Time', 'utc'=>'UTC-05', 'offset'=>'-5'),
        array('abbr'=>'CST', 'name'=>'Cuba Standard Time', 'utc'=>'UTC-05', 'offset'=>'-5'),
        array('abbr'=>'EASST', 'name'=>'Easter Island Standard Summer Time', 'utc'=>'UTC-05', 'offset'=>'-5'),
        array('abbr'=>'ECT', 'name'=>'Ecuador Time', 'utc'=>'UTC-05', 'offset'=>'-5'),
        array('abbr'=>'EST', 'name'=>'Eastern Standard Time (North America)', 'utc'=>'UTC-05', 'offset'=>'-5'),
        array('abbr'=>'PET', 'name'=>'Peru Time', 'utc'=>'UTC-05', 'offset'=>'-5'),
        array('abbr'=>'VET', 'name'=>'Venezuelan Standard Time', 'utc'=>'UTC-04:30', 'offset'=>'-04:30'),
        array('abbr'=>'AMT', 'name'=>'Amazon Time (Brazil)[2]', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'AST', 'name'=>'Atlantic Standard Time', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'BOT', 'name'=>'Bolivia Time', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'CDT', 'name'=>'Cuba Daylight Time[3]', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'CLT', 'name'=>'Chile Standard Time', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'COST', 'name'=>'Colombia Summer Time', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'ECT', 'name'=>'Eastern Caribbean Time (does not recognise DST)', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'EDT', 'name'=>'Eastern Daylight Time (North America)', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'FKT', 'name'=>'Falkland Islands Time', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'GYT', 'name'=>'Guyana Time', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'PYT', 'name'=>'Paraguay Time (Brazil)[7]', 'utc'=>'UTC-04', 'offset'=>'-4'),
        array('abbr'=>'NST', 'name'=>'Newfoundland Standard Time', 'utc'=>'UTC-03:30', 'offset'=>'-03:30'),
        array('abbr'=>'NT', 'name'=>'Newfoundland Time', 'utc'=>'UTC-03:30', 'offset'=>'-03:30'),
        array('abbr'=>'ADT', 'name'=>'Atlantic Daylight Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'AMST', 'name'=>'Amazon Summer Time (Brazil)[1]', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'ART', 'name'=>'Argentina Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'BRT', 'name'=>'Brasilia Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'CLST', 'name'=>'Chile Summer Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'FKST', 'name'=>'Falkland Islands Standard Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'FKST', 'name'=>'Falkland Islands Summer Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'GFT', 'name'=>'French Guiana Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'PMST', 'name'=>'Saint Pierre and Miquelon Standard Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'PYST', 'name'=>'Paraguay Summer Time (Brazil)', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'ROTT', 'name'=>'Rothera Research Station Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'SRT', 'name'=>'Suriname Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'UYT', 'name'=>'Uruguay Standard Time', 'utc'=>'UTC-03', 'offset'=>'-3'),
        array('abbr'=>'NDT', 'name'=>'Newfoundland Daylight Time', 'utc'=>'UTC-02:30', 'offset'=>'-02:30'),
        array('abbr'=>'FNT', 'name'=>'Fernando de Noronha Time', 'utc'=>'UTC-02', 'offset'=>'-2'),
        array('abbr'=>'GST', 'name'=>'South Georgia and the South Sandwich Islands', 'utc'=>'UTC-02', 'offset'=>'-2'),
        array('abbr'=>'PMDT', 'name'=>'Saint Pierre and Miquelon Daylight time', 'utc'=>'UTC-02', 'offset'=>'-2'),
        array('abbr'=>'UYST', 'name'=>'Uruguay Summer Time', 'utc'=>'UTC-02', 'offset'=>'-2'),
        array('abbr'=>'AZOST', 'name'=>'Azores Standard Time', 'utc'=>'UTC-01', 'offset'=>'-1'),
        array('abbr'=>'CVT', 'name'=>'Cape Verde Time', 'utc'=>'UTC-01', 'offset'=>'-1'),
        array('abbr'=>'EGT', 'name'=>'Eastern Greenland Time', 'utc'=>'UTC-01', 'offset'=>'-1'),
        array('abbr'=>'GMT', 'name'=>'Greenwich Mean Time', 'utc'=>'UTC', 'offset'=>'0'),
        array('abbr'=>'UCT', 'name'=>'Coordinated Universal Time', 'utc'=>'UTC', 'offset'=>'0'),
        array('abbr'=>'WET', 'name'=>'Western European Time', 'utc'=>'UTC', 'offset'=>'0'),
        array('abbr'=>'Z', 'name'=>'Zulu Time (Coordinated Universal Time)', 'utc'=>'UTC', 'offset'=>'0'),
        array('abbr'=>'EGST', 'name'=>'Eastern Greenland Summer Time', 'utc'=>'UTC+00', 'offset'=>'0'),
        array('abbr'=>'BST', 'name'=>'British Summer Time (British Standard Time from Feb 1968 to Oct 1971)', 'utc'=>'UTC+01', 'offset'=>'1'),
        array('abbr'=>'CET', 'name'=>'Central European Time', 'utc'=>'UTC+01', 'offset'=>'1'),
        array('abbr'=>'DFT', 'name'=>'AIX specific equivalent of Central European Time', 'utc'=>'UTC+01', 'offset'=>'1'),
        array('abbr'=>'IST', 'name'=>'Irish Standard Time', 'utc'=>'UTC+01', 'offset'=>'1'),
        array('abbr'=>'MET', 'name'=>'Middle European Time Same zone as CET', 'utc'=>'UTC+01', 'offset'=>'1'),
        array('abbr'=>'WAT', 'name'=>'West Africa Time', 'utc'=>'UTC+01', 'offset'=>'1'),
        array('abbr'=>'WEDT', 'name'=>'Western European Daylight Time', 'utc'=>'UTC+01', 'offset'=>'1'),
        array('abbr'=>'WEST', 'name'=>'Western European Summer Time', 'utc'=>'UTC+01', 'offset'=>'1'),
        array('abbr'=>'CAT', 'name'=>'Central Africa Time', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'CEDT', 'name'=>'Central European Daylight Time', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'CEST', 'name'=>'Central European Summer Time (Cf. HAEC)', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'EET', 'name'=>'Eastern European Time', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'HAEC', 'name'=>'Heure Avancée d\'Europe Centrale francised name for CEST', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'IST', 'name'=>'Israel Standard Time', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'MEST', 'name'=>'Middle European Saving Time Same zone as CEST', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'SAST', 'name'=>'South African Standard Time', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'WAST', 'name'=>'West Africa Summer Time', 'utc'=>'UTC+02', 'offset'=>'2'),
        array('abbr'=>'AST', 'name'=>'Arabia Standard Time', 'utc'=>'UTC+03', 'offset'=>'3'),
        array('abbr'=>'EAT', 'name'=>'East Africa Time', 'utc'=>'UTC+03', 'offset'=>'3'),
        array('abbr'=>'EEDT', 'name'=>'Eastern European Daylight Time', 'utc'=>'UTC+03', 'offset'=>'3'),
        array('abbr'=>'EEST', 'name'=>'Eastern European Summer Time', 'utc'=>'UTC+03', 'offset'=>'3'),
        array('abbr'=>'FET', 'name'=>'Further-eastern European Time', 'utc'=>'UTC+03', 'offset'=>'3'),
        array('abbr'=>'IDT', 'name'=>'Israel Daylight Time', 'utc'=>'UTC+03', 'offset'=>'3'),
        array('abbr'=>'IOT', 'name'=>'Indian Ocean Time', 'utc'=>'UTC+03', 'offset'=>'3'),
        array('abbr'=>'SYOT', 'name'=>'Showa Station Time', 'utc'=>'UTC+03', 'offset'=>'3'),
        array('abbr'=>'IRST', 'name'=>'Iran Standard Time', 'utc'=>'UTC+03:30', 'offset'=>'+03:30'),
        array('abbr'=>'AMT', 'name'=>'Armenia Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'AZT', 'name'=>'Azerbaijan Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'GET', 'name'=>'Georgia Standard Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'GST', 'name'=>'Gulf Standard Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'MSK', 'name'=>'Moscow Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'MUT', 'name'=>'Mauritius Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'RET', 'name'=>'Réunion Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'SAMT', 'name'=>'Samara Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'SCT', 'name'=>'Seychelles Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'VOLT', 'name'=>'Volgograd Time', 'utc'=>'UTC+04', 'offset'=>'4'),
        array('abbr'=>'AFT', 'name'=>'Afghanistan Time', 'utc'=>'UTC+04:30', 'offset'=>'+04:30'),
        array('abbr'=>'AMST', 'name'=>'Armenia Summer Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'HMT', 'name'=>'Heard and McDonald Islands Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'MAWT', 'name'=>'Mawson Station Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'MVT', 'name'=>'Maldives Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'ORAT', 'name'=>'Oral Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'PKT', 'name'=>'Pakistan Standard Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'TFT', 'name'=>'Indian/Kerguelen', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'TJT', 'name'=>'Tajikistan Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'TMT', 'name'=>'Turkmenistan Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'UZT', 'name'=>'Uzbekistan Time', 'utc'=>'UTC+05', 'offset'=>'5'),
        array('abbr'=>'IST', 'name'=>'Indian Standard Time', 'utc'=>'UTC+05:30', 'offset'=>'+05:30'),
        array('abbr'=>'SLST', 'name'=>'Sri Lanka Time', 'utc'=>'UTC+05:30', 'offset'=>'+05:30'),
        array('abbr'=>'NPT', 'name'=>'Nepal Time', 'utc'=>'UTC+05:45', 'offset'=>'+05:45'),
        array('abbr'=>'BIOT', 'name'=>'British Indian Ocean Time', 'utc'=>'UTC+06', 'offset'=>'6'),
        array('abbr'=>'BST', 'name'=>'Bangladesh Standard Time', 'utc'=>'UTC+06', 'offset'=>'6'),
        array('abbr'=>'BTT', 'name'=>'Bhutan Time', 'utc'=>'UTC+06', 'offset'=>'6'),
        array('abbr'=>'KGT', 'name'=>'Kyrgyzstan time', 'utc'=>'UTC+06', 'offset'=>'6'),
        array('abbr'=>'VOST', 'name'=>'Vostok Station Time', 'utc'=>'UTC+06', 'offset'=>'6'),
        array('abbr'=>'YEKT', 'name'=>'Yekaterinburg Time', 'utc'=>'UTC+06', 'offset'=>'6'),
        array('abbr'=>'CCT', 'name'=>'Cocos Islands Time', 'utc'=>'UTC+06:30', 'offset'=>'+06:30'),
        array('abbr'=>'MMT', 'name'=>'Myanmar Time', 'utc'=>'UTC+06:30', 'offset'=>'+06:30'),
        array('abbr'=>'MST', 'name'=>'Myanmar Standard Time', 'utc'=>'UTC+06:30', 'offset'=>'+06:30'),
        array('abbr'=>'CXT', 'name'=>'Christmas Island Time', 'utc'=>'UTC+07', 'offset'=>'7'),
        array('abbr'=>'DAVT', 'name'=>'Davis Time', 'utc'=>'UTC+07', 'offset'=>'7'),
        array('abbr'=>'HOVT', 'name'=>'Khovd Time', 'utc'=>'UTC+07', 'offset'=>'7'),
        array('abbr'=>'ICT', 'name'=>'Indochina Time', 'utc'=>'UTC+07', 'offset'=>'7'),
        array('abbr'=>'KRAT', 'name'=>'Krasnoyarsk Time', 'utc'=>'UTC+07', 'offset'=>'7'),
        array('abbr'=>'OMST', 'name'=>'Omsk Time', 'utc'=>'UTC+07', 'offset'=>'7'),
        array('abbr'=>'THA', 'name'=>'Thailand Standard Time', 'utc'=>'UTC+07', 'offset'=>'7'),
        array('abbr'=>'ACT', 'name'=>'ASEAN Common Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'AWST', 'name'=>'Australian Western Standard Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'BDT', 'name'=>'Brunei Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'CHOT', 'name'=>'Choibalsan', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'CIT', 'name'=>'Central Indonesia Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'CST', 'name'=>'China Standard Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'CT', 'name'=>'China time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'HKT', 'name'=>'Hong Kong Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'IRDT', 'name'=>'Iran Daylight Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'MST', 'name'=>'Malaysia Standard Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'MYT', 'name'=>'Malaysia Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'PHT', 'name'=>'Philippine Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'SGT', 'name'=>'Singapore Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'SST', 'name'=>'Singapore Standard Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'ULAT', 'name'=>'Ulaanbaatar Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'WST', 'name'=>'Western Standard Time', 'utc'=>'UTC+08', 'offset'=>'8'),
        array('abbr'=>'CWST', 'name'=>'Central Western Standard Time (Australia)', 'utc'=>'UTC+08:45', 'offset'=>'+08:45'),
        array('abbr'=>'AWDT', 'name'=>'Australian Western Daylight Time', 'utc'=>'UTC+09', 'offset'=>'9'),
        array('abbr'=>'EIT', 'name'=>'Eastern Indonesian Time', 'utc'=>'UTC+09', 'offset'=>'9'),
        array('abbr'=>'IRKT', 'name'=>'Irkutsk Time', 'utc'=>'UTC+09', 'offset'=>'9'),
        array('abbr'=>'JST', 'name'=>'Japan Standard Time', 'utc'=>'UTC+09', 'offset'=>'9'),
        array('abbr'=>'KST', 'name'=>'Korea Standard Time', 'utc'=>'UTC+09', 'offset'=>'9'),
        array('abbr'=>'TLT', 'name'=>'Timor Leste Time', 'utc'=>'UTC+09', 'offset'=>'9'),
        array('abbr'=>'ACST', 'name'=>'Australian Central Standard Time', 'utc'=>'UTC+09:30', 'offset'=>'+09:30'),
        array('abbr'=>'CST', 'name'=>'Central Standard Time (Australia)', 'utc'=>'UTC+09:30', 'offset'=>'+09:30'),
        array('abbr'=>'AEST', 'name'=>'Australian Eastern Standard Time', 'utc'=>'UTC+10', 'offset'=>'10'),
        array('abbr'=>'ChST', 'name'=>'Chamorro Standard Time', 'utc'=>'UTC+10', 'offset'=>'10'),
        array('abbr'=>'CHUT', 'name'=>'Chuuk Time', 'utc'=>'UTC+10', 'offset'=>'10'),
        array('abbr'=>'DDUT', 'name'=>'Dumont d\'Urville Time', 'utc'=>'UTC+10', 'offset'=>'10'),
        array('abbr'=>'EST', 'name'=>'Eastern Standard Time (Australia)', 'utc'=>'UTC+10', 'offset'=>'10'),
        array('abbr'=>'PGT', 'name'=>'Papua New Guinea Time', 'utc'=>'UTC+10', 'offset'=>'10'),
        array('abbr'=>'VLAT', 'name'=>'Vladivostok Time', 'utc'=>'UTC+10', 'offset'=>'10'),
        array('abbr'=>'YAKT', 'name'=>'Yakutsk Time', 'utc'=>'UTC+10', 'offset'=>'10'),
        array('abbr'=>'ACDT', 'name'=>'Australian Central Daylight Time', 'utc'=>'UTC+10:30', 'offset'=>'+10:30'),
        array('abbr'=>'CST', 'name'=>'Central Summer Time (Australia)', 'utc'=>'UTC+10:30', 'offset'=>'+10:30'),
        array('abbr'=>'LHST', 'name'=>'Lord Howe Standard Time', 'utc'=>'UTC+10:30', 'offset'=>'+10:30'),
        array('abbr'=>'AEDT', 'name'=>'Australian Eastern Daylight Time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'KOST', 'name'=>'Kosrae Time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'LHST', 'name'=>'Lord Howe Summer Time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'MIST', 'name'=>'Macquarie Island Station Time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'NCT', 'name'=>'New Caledonia Time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'PONT', 'name'=>'Pohnpei Standard Time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'SAKT', 'name'=>'Sakhalin Island time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'SBT', 'name'=>'Solomon Islands Time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'VUT', 'name'=>'Vanuatu Time', 'utc'=>'UTC+11', 'offset'=>'11'),
        array('abbr'=>'NFT', 'name'=>'Norfolk Time', 'utc'=>'UTC+11:30', 'offset'=>'+11:30'),
        array('abbr'=>'FJT', 'name'=>'Fiji Time', 'utc'=>'UTC+12', 'offset'=>'12'),
        array('abbr'=>'GILT', 'name'=>'Gilbert Island Time', 'utc'=>'UTC+12', 'offset'=>'12'),
        array('abbr'=>'MAGT', 'name'=>'Magadan Time', 'utc'=>'UTC+12', 'offset'=>'12'),
        array('abbr'=>'MHT', 'name'=>'Marshall Islands', 'utc'=>'UTC+12', 'offset'=>'12'),
        array('abbr'=>'NZST', 'name'=>'New Zealand Standard Time', 'utc'=>'UTC+12', 'offset'=>'12'),
        array('abbr'=>'PETT', 'name'=>'Kamchatka Time', 'utc'=>'UTC+12', 'offset'=>'12'),
        array('abbr'=>'TVT', 'name'=>'Tuvalu Time', 'utc'=>'UTC+12', 'offset'=>'12'),
        array('abbr'=>'WAKT', 'name'=>'Wake Island Time', 'utc'=>'UTC+12', 'offset'=>'12'),
        array('abbr'=>'CHAST', 'name'=>'Chatham Standard Time', 'utc'=>'UTC+12:45', 'offset'=>'+12:45'),
        array('abbr'=>'NZDT', 'name'=>'New Zealand Daylight Time', 'utc'=>'UTC+13', 'offset'=>'13'),
        array('abbr'=>'PHOT', 'name'=>'Phoenix Island Time', 'utc'=>'UTC+13', 'offset'=>'13'),
        array('abbr'=>'TOT', 'name'=>'Tonga Time', 'utc'=>'UTC+13', 'offset'=>'13'),
        array('abbr'=>'CHADT', 'name'=>'Chatham Daylight Time', 'utc'=>'UTC+13:45', 'offset'=>'+13:45'),
        array('abbr'=>'LINT', 'name'=>'Line Islands Time', 'utc'=>'UTC+14', 'offset'=>'14'),
        array('abbr'=>'TKT', 'name'=>'Tokelau Time', 'utc'=>'UTC+14', 'offset'=>'14'),
    );



    public function run()
    {

        foreach($this->timezones as $timezone)
        {

            Timezone::create([
                'abbr'=>$timezone['abbr'],
                'name'=>$timezone['name'],
                'utc'=>$timezone['utc'],
                'offset'=>$timezone['offset'],
            ]);

        }

    }
}
